kind: Service
apiVersion: v1
metadata:
  name: {{ template "schedulerservice.name" . }}
  labels:
    service-name: {{ .Values.serviceName }}
    app: {{ template "schedulerservice.name" . }}  
spec:
  selector:
    app: {{ template "schedulerservice.name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
