version: "2.1"
services:
  webapi:
    build: ./artifacts/PreferencesWebApi
    env_file:
      - docker-compose-local.env
    volumes:
      - ./artifacts/logs:/app/logs
    ports:
      - "3001:80"
    depends_on:
      - schema
  schema:
    build: ./database
    env_file:
      - docker-compose-local.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]
    env_file:
      - docker-compose-local.env
    ports:
      - "3306:3306"  