{{ if .Values.webtools.deploy }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trex.deployname" . }}-webtools
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
    immutable-cluster: "true"
    mutable-cluster: "true"
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.webtools.replicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-webtools
        immutable-cluster: "true"
        mutable-cluster: "true"

    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- with .Values.nodeSelector.none }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations.none }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.Webtools
        imagePullPolicy: Always

        resources:
{{ toYaml .Values.webtools.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "trex.config" . }}

        command: ["dotnet"]
        args: ["VSS.TRex.Webtools.dll"]

        ports:
{{ toYaml .Values.trexPorts | indent 8 }}

        volumeMounts:
        # Mounting the storage with the Ignite configuration.
        #- mountPath: "/data/ignite"
        #  name: ignite-storage
        env:
          - name: IGNITE_HOME
            value: "/trex/"
          - name: IS_KUBERNETES
            value: "true"
          - name: DEPLOYED_ENV
            value: {{ .Values.environment }}
          - name: TREX_IGNITE_JVM_MAX_HEAP_SIZE_MB
            value: {{ .Values.webtools.javaHeapMaxSizeMb | quote}}
          - name: TREX_IGNITE_JVM_INITIAL_HEAP_SIZE_MB
            value: {{ .Values.webtools.javaHeapInitialSizeMb | quote }}  

{{ end }}