version: "3"
services:
  webapi:
    build: ./Artifacts/WebApi
    ports:
      - "80:80"
    env_file:
      - docker-compose-local.env
    volumes:
      - .\artifacts\webapi\logs:c:\app\logs
    depends_on:
      - mockprojectwebapi
  mockprojectwebapi:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-mock-webapi:latest
    env_file:
      - docker-compose-local.env
    ports:
      - "5001:5001"
networks:
  default:
    external:
      name: nat
