kind: Service
apiVersion: v1
metadata:
  name: {{ template "trex.deployname" . }}-gateway
  labels:
    service-name: {{ .Values.serviceName }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    component: {{ template "trex.deployname" . }}-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP