apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  labels:
    app: {{ template "trex.deployname" . }}
    component: {{ template "trex.deployname" . }}.serviceaccount
    chart: {{ template "trex.chart" . }}
