resources:
- repo: self
queue:
  name: kubernetes-vsts-agents
#Your build pipeline references an undefined variable named ‘Parameters.serverEndpoint’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.jobName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.jobName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.jobName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.serverEndpoint’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.jobName’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
steps:
- task: JenkinsQueueJob@2
  displayName: "Queue Jenkins Job: vss-fileaccess-webapi"
  inputs:
    serverEndpoint: '$(Parameters.serverEndpoint)'
    jobName: 'vss-fileaccess-webapi'
    isParameterizedJob: true
    jobParameters: |
     VSTS_BUILD_NUMBER=$(Build.BuildNumber)
     BRANCH_NAME=$(Build.SourceBranch)

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: XUnit
    testResultsFiles: 'team-results/**/TestResults/UnitTests/**/*.xml'
    searchFolder: '$(Build.ArtifactStagingDirectory)/jenkinsResults/$(Parameters.jobName)/'
    mergeTestResults: true

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.ArtifactStagingDirectory)/jenkinsResults/$(Parameters.jobName)/team-results/**/TestResults/TestCoverage/*.xml'

- task: PublishTestResults@2
  displayName: Publish Test Results - Integration
  inputs:
    testRunner: XUnit
    testResultsFiles: 'team-results/**/AcceptanceTests/tests/**/TestResults/*.xml'
    searchFolder: '$(Build.ArtifactStagingDirectory)/jenkinsResults/$(Parameters.jobName)/'
    mergeTestResults: true

- task: JenkinsDownloadArtifacts@1
  displayName: Download artifacts produced by vss-fileaccess-webapi
  inputs:
    jenkinsServerConnection: '$(Parameters.serverEndpoint)'
    jobName: '$(Parameters.jobName)'
    saveTo: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: chart"
  inputs:
    ArtifactName: chart


