version: '2'
services:
  webapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-project-webapi:latest
    env_file:
     - docker-compose-dev.env
    ports:
     - "3001:80"
    depends_on:
      - schema
  masterdataconsumercustomer:
    build: ./Artifacts/MasterDataConsumer
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-project-masterdataconsumer:latest
    env_file:
     - docker-compose-dev.env
    environment:
    - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ICustomerEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka
  masterdataconsumergeofence:
    build: ./Artifacts/MasterDataConsumer
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-project-masterdataconsumer:latest
    env_file:
     - docker-compose-dev.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.IGeofenceEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka     
  masterdataconsumersubscription:
    build: ./Artifacts/MasterDataConsumer
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-project-masterdataconsumer:latest
    env_file:
     - docker-compose-dev.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ISubscriptionEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka
  schema:
    build: ./Database
    env_file:
     - docker-compose-dev.env