version: '2'
services:
  webapi:
    build: ./artifacts/WebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./artifacts/logs:/app/logs 
    depends_on:
      - schema
  schema:
    build: ./database
    env_file:
     - docker-compose.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci] 
    env_file:
     - docker-compose.env
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi