version: '2'
services:
  webapi:
    build: ./artifacts/VSS.Productivity3D.Scheduler.WebApi
    env_file:
     - docker-compose-local.env
    volumes:
      - ./artifacts/logs:/app/logs
    ports:
     - "3001:80"
    depends_on:
      - schema
      - filterschema
      - db
  filterschema:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-productivity3d-filter-db:latest
    env_file:
     - docker-compose-local.env
    environment:
     - MYSQL_DATABASE_NAME=VSS-Productivity3D-Filter
    depends_on:
      - db
  schema:
    build: ./database
    env_file:
     - docker-compose-local.env
    environment:
     - MYSQL_SERVER_NAME=db
     - MYSQL_DATABASE_NAME=VSS-Productivity3D-Scheduler
     - MYSQL_PORT=3306
     - MYSQL_USERNAME=root
     - MYSQL_ROOT_PASSWORD=abc123
    depends_on:
     - db
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    env_file:
     - docker-compose-local.env
    ports:
      - "3306:3306" 
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose-local.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi