version: '2'
services:
  webapi:
    build: ./Artifacts/WebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
  datafeed:
    build: ./Artifacts/DatafeedService
    env_file:
     - docker-compose.env
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka
  schema:
    build: ./Database
    env_file:
     - docker-compose.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci] 
    env_file:
     - docker-compose.env
  zookeeper:
    image: wurstmeister/zookeeper:latest
  kafka:
    image: wurstmeister/kafka:latest
    env_file:
     - docker-compose.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi
      - datafeed
      - kafka