version: '3'
services:
  webapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-raptor-webapi:latest
    env_file:
     - docker-compose-dev.env
    ports:
     - "5001:80"
  mockprojectwebapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-mockproject-webapi:latest
    env_file:
     - docker-compose.env
    ports:
     - "5001:5001"
networks:
  default:
    external:
      name: nat
 