version: '2.1'
services:
  webapi:
    build: ./Artifacts/WebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./Artifacts/Logs:/app/logs
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi