version: '2'
services:
  webapi:
    build: ./Artifacts/ProjectWebApi
    env_file:
     - docker-compose-local.env
    volumes:
      - ./Artifacts/Logs:/app/logs 
    ports:
     - "3001:80"
    depends_on:
      - schema
  masterdataconsumercustomer:
    build: ./Artifacts/MasterDataConsumer
    image: masterdataconsumercustomer
    env_file:
     - docker-compose-local.env
    environment:
    - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ICustomerEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka     
  masterdataconsumerproject:
    build: ./Artifacts/MasterDataConsumer
    image: masterdataconsumerproject
    env_file:
     - docker-compose-local.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.IProjectEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka     
  masterdataconsumergeofence:
    build: ./Artifacts/MasterDataConsumer
    image: masterdataconsumergeofence
    env_file:
     - docker-compose-local.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.IGeofenceEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka     
  masterdataconsumersubscription:
    build: ./Artifacts/MasterDataConsumer
    image: masterdataconsumersubscription
    env_file:
     - docker-compose-local.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ISubscriptionEvent
    volumes:
      - ./Artifacts/Logs:/app/logs
    depends_on:
      - schema
      - kafka
  schema:
    build: ./Database
    env_file:
     - docker-compose-local.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci] 
    env_file:
     - docker-compose-local.env
    ports:
      - "3306:3306"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    env_file:
     - docker-compose-local.env  
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_CREATE_TOPICS=VSS.Interfaces.Events.MasterData.ICustomerEvent-Project:1:1,VSS.Interfaces.Events.MasterData.IProjectEvent-Project:1:1,VSS.Interfaces.Events.MasterData.IGeofenceEvent-Project:1:1,VSS.Interfaces.Events.MasterData.ISubscriptionEvent-Project:1:1
    ports:
     - "9092:9092"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose-local.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi
      - masterdataconsumercustomer
      - masterdataconsumerproject
      - masterdataconsumergeofence
      - masterdataconsumersubscription
      - kafka