version: '3'
services:
  webapi:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-raptor-webapi:latest
    environment:
     - PROJECT_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/project?includeLandfill=true
     - GEOFENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-geofenceservice/1.0
     - PREFERENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-preferenceservice/1.0
     - IMPORTED_FILE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/importedfiles
     - CUSTOMERSERVICE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-customerservice/1.0/Customers/me
     - PROJECT_SETTINGS_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/projectsettings
     - FILTER_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-3Dfilter/1.0/filter
     - GEOFENCE_CACHE_LIFE=00:15:00
     - PROJECT_CACHE_LIFE=00:15:00
     - IMPORTED_FILE_CACHE_LIFE=00:15:00
     - CUSTOMERSERVICE_CACHE_LIFE=00:15:00
     - PROJECT_SETTINGS_CACHE_LIFE=00:15:00
     - ELEVATION_EXTENTS_CACHE_LIFE=00:15:00
     - ASNODEIP=10.97.96.134
     - IONODEIP=10.97.96.92
     - SHAREUNC=\\dev-iolv01.vssengg.com\ProductionData
     - TCCBASEURL=https://www.myconnectedsite.com
     - TCCUSERNAME=vldev
     - TCCPWD=vldev_key
     - TCCORG=vldev
     - TCCFILESPACEID=u3bdc38d6-1afe-470e-8c1c-fc241d4c5e01
     - TCCFILESPACENAME=vldatastore-dev
     - TILE_RENDER_MAX_ZOOM_LEVEL=21
     - TILE_RENDER_MAX_ZOOM_RANGE=14
     - TILE_RENDER_WAIT_INTERVAL=2000
     - TILE_RENDER_JOB_TIMEOUT=00:00:10
    ports:
     - "5001:80"
    restart: always
    deploy:
      replicas: 1
networks:
  default:
    external:
      name: nat
 