version: '2'
services:
  webapi:
    build: ./artifacts/ProjectWebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./artifacts/logs:/app/logs
    depends_on:
      - schema
  masterdataconsumercustomer:
    build: ./artifacts/MasterDataConsumer
    image: masterdataconsumercustomer
    env_file:
     - docker-compose.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ICustomerEvent
    volumes:
      - ./artifacts/logs:/app/logs
    depends_on:
      - schema
      - kafka
  masterdataconsumerproject:
    build: ./artifacts/MasterDataConsumer
    image: masterdataconsumerproject
    env_file:
     - docker-compose.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.IProjectEvent
    volumes:
      - ./artifacts/logs:/app/logs
    depends_on:
      - schema
      - kafka
  masterdataconsumergeofence:
    build: ./artifacts/MasterDataConsumer
    image: masterdataconsumergeofence
    env_file:
     - docker-compose.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.IGeofenceEvent
    volumes:
      - ./artifacts/logs:/app/logs
    depends_on:
      - schema
      - kafka
  masterdataconsumersubscription:
    build: ./artifacts/MasterDataConsumer
    image: masterdataconsumersubscription
    env_file:
     - docker-compose.env
    environment:
     - KAFKA_TOPICS=VSS.Interfaces.Events.MasterData.ISubscriptionEvent
    volumes:
      - ./artifacts/logs:/app/logs
    depends_on:
      - schema
      - kafka
  schema:
    build: ./database
    env_file:
     - docker-compose.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15 
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci] 
    env_file:
     - docker-compose.env
  zookeeper:
    image: wurstmeister/zookeeper:latest
  kafka:
    image: wurstmeister/kafka:latest
    env_file:
     - docker-compose.env
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - zookeeper
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi
      - masterdataconsumercustomer
      - masterdataconsumerproject
      - masterdataconsumergeofence
      - masterdataconsumersubscription
      - kafka