{{- $filename := printf "%s.txt" .Values.environment -}}
{{- $configName := printf "%s-cfg-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
{{- $name :=       printf "%s-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  labels:
    app: {{ $name }}
    release: "{{ $name }}"
data:
  {{ range .Files.Lines $filename }}
  {{ . }}{{ end }}

