{{- $fdqn := printf "%s.%s" .Values.environment .Values.rootDomain -}}
{{- $name :=       printf "%s-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}.{{ $fdqn }}
      http:
        paths:
          - backend:
              serviceName: {{ $name }} 
              servicePort: 80
    {{- end -}}
