{{- $filename := printf "%s.txt" .Values.environment -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-{{ .Values.environment }}-{{ .Values.image.tag }}
data:
  {{ range .Files.Lines $filename }}
  {{ . }}{{ end }}

