apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}-consumer
  labels:
    app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.consumerImage.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.consumerImage.tag }}-consumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.consumerImage.tag }}
    spec:
      containers:
      - image: image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:{{ .Values.consumerImage.tag }}
        name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.consumerImage.tag }}-consumer        
        resources:
{{ toYaml .Values.resources | indent 12 }}
      envFrom:
      - configMapRef:
          name: {{ .Release.Name }}-config-{{ .Values.environment }}-{{ .Values.image.tag }}
        imagePullPolicy: Always


