version: "3"
services:
  webapi:
    build:
      context: ./artifacts/WebApi
      dockerfile: ../../build/Dockerfile.build
    env_file:
      - docker-compose-local.env
    volumes:
      - ./artifacts/logs:/app/logs
    ports:
      - "3001:80"
