# Common values for vlmd-device
global:
  componentName: "vlmd-device"
  configmap:
    s3path: s3://vss-ci-builds/VSS.MasterData.WebAPI/Device/__Branch__/__BuildId__/db_scripts

  # Automatically have flyway perform the migration!
  flyway:
    enabled: false
  image:
    repository: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vlmd-device
    tag: __Branch__-__BuildId__
    pullPolicy: Always
  ingress:
    enabled: true
    # Used to create an Ingress record.
    # Release automation will dynamically create hosts and target.
    hosts:
      - __ENVIRONMENT__-vlmd-device__DOMAIN__
    annotations:
      kubernetes.io/ingress.class: nginx
      external-dns.alpha.kubernetes.io/target: __ENDPOINT__
    paths:
      - /v1
      - /v2
      - /healthz
      - /swagger