{{- $name :=       printf "%s-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
{{- $configName := printf "%s-cfg-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-csr
  labels:
    app: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      initContainers:
      - name: init-db
        image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest
        tty: true
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        - configMapRef:
            name: {{ .Values.globalConfig }}
        - secretRef:
            name: {{ .Values.globalConfig }}-secret
      containers:
      - image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:{{ .Values.consumerImage.tag }}
        name: {{ $name }}-csr     
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        - configMapRef:
            name: {{ .Values.globalConfig }}
        - secretRef:
            name: {{ .Values.globalConfig }}-secret
        imagePullPolicy: Always


