{{- $configName := printf "%s-cfg-%s" .Release.Name .Values.environment | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "projectservice.name" . }}
  labels:
    app: {{ template "projectservice.name" . }}
spec:
  replicas: {{ default 1 .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "projectservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "projectservice.name" . }}
    spec:
      serviceAccount: {{ .Values.environment }}-service-account
      containers:
      - image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-project-webapi:{{ .Values.image.tag }}
        name: {{ template "projectservice.name" . }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 80
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        - configMapRef:
            name: {{ .Values.globalConfig }}
        - secretRef:
            name: {{ .Values.globalConfig }}-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 80
