{{- $configName := printf "%s-config-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}-webapi
  labels:
    app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
    spec:
      containers:
      - image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-landfill:{{ .Values.image.tag }}
        name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag | lower }}
        command: ["dotnet"]
        args: ["LandfillService.WebApi.netcore.dll"]
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ping
            port: 80
        readinessProbe:
          httpGet:
            path: /ping
            port: 80
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        - configMapRef:
            name: {{ .Values.globalConfig }}
        - secretRef:
            name: {{ .Values.globalConfig }}-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 80
