# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: eks.ccss.cloud

serviceAccountName: trex

image:
  repository: "940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.ccss.cloud

service:
  type: ClusterIP

applicationServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

designElevation:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

gateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-immutable
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi

immutableData:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi

mutableData:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 900m
      memory: 2048Mi
  storage:
    size: 10Gi
    className: aws-efs
    
  environment:
    enableTfa: true
    enableTagFileArchiving: true
    enableTagFileArchivingMetadata: false
    minTagFileLength: 99
    tagfileArchiveFolder: ""

mutableGateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-mutable
  resources:
    requests:
      cpu: 300m
      memory: 1Gi

psnode:
  replicaCount: 1
  javaHeapMaxSizeMb: 4096
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 900m
      memory: 7.0Gi
  storage:
    size: 10Gi
    className: aws-efs
  
qmeshServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100


reportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

tileServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

tinExportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1026
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

utilities:
  deploy: true
  replicaCount: 0
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

webtools:
  deploy: true
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi


# kubectl label nodes <node> vss/application=trex
nodeSelector: 
  highMemory:
    vss/application: trexbigmem
  generalPurpose:
    vss/application: trexgp
  none: {}


# kubectl taint nodes <node> dedicated=trex:NoSchedule
tolerations: 
  highMemory:
  - key: "dedicated"
    operator: "Equal" 
    value: "trexbigmem"
    effect: "NoSchedule"
  generalPurpose:
  - key: "dedicated"
    operator: "Equal" 
    value: "trexgp"
    effect: "NoSchedule"
  none: []


affinity: {}
