# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: eks.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.vspengg.com

service:
  type: ClusterIP

applicationServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

designElevation:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

gateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  serviceDiscoveryName: trex-service-immutable
  resources:
    requests:
      cpu: 300m
      memory: 768Mi

immutableData:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

mutableData:
  replicaCount: 2
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi
  storage:
    size: 10Gi
    className: efs
    
  environment:
    enableTfa: false
    enableTagFileArchiving: false
    enableTagFileArchivingMetadata: false
    minTagFileLength: 99
    tagfileArchiveFolder: ""

mutableGateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  serviceDiscoveryName: trex-service-mutable
  resources:
    requests:
      cpu: 300m
      memory: 768Mi

psnode:
  replicaCount: 2
  javaHeapMaxSizeMb: 4096
  resources: 
    requests:
      cpu: 500m
      memory: 6.0Gi
  storage:
    size: 10Gi
    className: efs
  

reportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources:
    requests:
      cpu: 300m
      memory: 1.0Gi

tileServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1.0Gi

tinExportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1.0Gi

utilities:
  replicaCount: 0
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 200m
      memory: 768Mi

webtools:
  replicaCount: 1
  javaHeapMaxSizeMb: 512
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}
