psnode:
  replicaCount: 4
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 3500m
      memory: 24Gi
  storage:
    size: 10Gi
    className: aws-efs
  
tileServer:
  autoscaling:
    minReplicas: 4
    maxReplicas: 20

