# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: eks.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.vspengg.com

service:
  type: ClusterIP

applicationServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

designElevation:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

gateway:
  replicaCount: 2
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-immutable
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi

immutableData:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi

mutableData:
  replicaCount: 2
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  storage:
    size: 10Gi
    className: efs
    
  environment:
    enableTfa: false
    enableTagFileArchiving: false
    enableTagFileArchivingMetadata: false
    minTagFileLength: 99
    tagfileArchiveFolder: ""

mutableGateway:
  replicaCount: 2
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-mutable
  resources:
    requests:
      cpu: 300m
      memory: 1Gi

psnode:
  replicaCount: 2
  javaHeapMaxSizeMb: 4096
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 500m
      memory: 6.0Gi
  storage:
    size: 10Gi
    className: efs
  

reportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

tileServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

tinExportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1026
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

utilities:
  replicaCount: 0
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 500m
      memory: 1Gi

webtools:
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 500m
      memory: 1Gi


# kubectl label nodes <node> vss/application=trex
nodeSelector: 
  vss/application: trex

# kubectl taint nodes <node> dedicated=trex:NoSchedule
tolerations: 
- key: "dedicated"
  operator: "Equal" 
  value: "trex"
  effect: "NoSchedule"

affinity: {}
