# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: eks.ccss.cloud

serviceAccountName: trex

image:
  repository: "940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-trex"
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.ccss.cloud

service:
  type: ClusterIP

applicationServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

designElevation:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 2Gi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

gateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-immutable
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 75

mutableData:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 900m
      memory: 4Gi
  storage:
    enabled: true
    size: 10Gi
    className: aws-efs
    
  environment:
    enableDeviceGateway: false
    enableTfa: true
    enableTagFileArchiving: true
    enableTagFileArchivingMetadata: false
    minTagFileLength: 99
    tagfileArchiveFolder: ""

mutableGateway:
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  serviceDiscoveryName: trex-service-mutable
  resources:
    requests:
      cpu: 300m
      memory: 1Gi

psnode:
  replicaCount: 1
  javaHeapMaxSizeMb: 4096
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 900m
      memory: 12.0Gi
  storage:
    enabled: true
    size: 10Gi
    className: aws-efs
  
qmeshServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

projectRebuilderServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

reportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources:
    requests:
      cpu: 300m
      memory: 1280Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

tileServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1024
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: true
      target: 100

tinExportServer:
  replicaCount: 1
  javaHeapMaxSizeMb: 1026
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1536Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    memory:
      enabled: false
      target: 0
    cpu:
      enabled: false
      target: 100

utilities:
  deploy: true
  replicaCount: 0
  deployServiceDeployerJob: false
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

webtools:
  deploy: true
  replicaCount: 1
  javaHeapMaxSizeMb: 768
  javaHeapInitialSizeMb: 768  
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi


# kubectl label nodes <node> vss/application=trex
nodeSelector: 
  enabled: true
  highMemory:
    vss/application: trexbigmem
  generalPurpose:
    vss/application: trexgp
  none: {}


# kubectl taint nodes <node> dedicated=trex:NoSchedule
tolerations: 
  enabled: true
  highMemory:
  - key: "dedicated"
    operator: "Equal" 
    value: "trexbigmem"
    effect: "NoSchedule"
  generalPurpose:
  - key: "dedicated"
    operator: "Equal" 
    value: "trexgp"
    effect: "NoSchedule"
  none: []

#Ports that trex uses, at some point we may split this into im/mutable mappings
trexPorts:
- containerPort: 80
  name: http
- containerPort: 8080 
  name: igniterestapi
- containerPort: 8088
  name: jmxprometheus
- containerPort: 47100
  name: spicoms
- containerPort: 47500
  name: spidisco
- containerPort: 48100
  name: spicommsmutable
- containerPort: 48500
  name: spidiscomutable
- containerPort: 49112
  name: ignitejmx
- containerPort: 10800
  name: ignitesql
- containerPort: 11211
  name: mutablecoms
- containerPort: 11212
  name: immutablecoms




affinity: {}
