{{- if .Values.gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trex.deployname" . }}-gateway
  labels:
    app: {{ template "trex.deployname" . }}
    component: {{ template "trex.deployname" . }}-gateway
    chart: {{ template "trex.chart" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "trex.deployname" . }}-gateway
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
{{- if .Values.gateway.autoscaling.cpu.enabled }}
{{- with .Values.gateway.autoscaling.cpu.target }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
{{- end }}
{{- end }}

{{- if .Values.gateway.autoscaling.memory.enabled }}
{{- with .Values.gateway.autoscaling.memory.target }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
{{- end }}
{{- end }}
{{- end }}