kind: Service
apiVersion: v1
metadata:
  name: projectservice-webapi
spec:
  externalTrafficPolicy: Local
  selector:
    app: projectservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice-deployment
  labels:
    app: projectservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectservice
  template:
    metadata:
      labels:
        app: projectservice
    spec:
      containers:
      - name: projectservice
        image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-project-webapi:{{.Values.dockerTag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_STORAGE
              value: {{default "minio" .Values.storage}}