kind: Service
apiVersion: v1
metadata:
  name: projectservice-webapi
spec:
  externalTrafficPolicy: Local
  selector:
    app: projectservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
