# An example of a Kubernetes configuration for Ignite pods deployment.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trex.fullname" . }}-{{ .Values.environment }}-{{ .Values.image.tag }}-webtools
  labels:
    app: {{ template "trex.name" . }}-{{ .Values.environment }}-{{ .Values.image.tag }}
    chart: {{ template "trex.chart" . }}
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.psNodeReplicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.name" . }}-{{ .Values.environment }}-{{ .Values.image.tag }}
        component: {{ template "trex.name" . }}-{{ .Values.environment }}-{{ .Values.image.tag }}-webtools

    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      #volumes:
        # Custom name for the storage that holds Ignite's configuration
        # which is example-kube.xml.
        # TODO Workout peristance!
        #- name: ignite-storage
        #  persistentVolumeClaim:
        #   # Must be equal to the PersistentVolumeClaim created before.
        #   claimName: ignite-volume-claim	
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        
        command: ["dotnet"]
        args: ["VSS.TRex.Webtools.dll"]

        #env:
        # Ignite's Docker image parameter. Adding the jar file that
        # contain TcpDiscoveryKubernetesIpFinder implementation.
        #- name: OPTION_LIBS
        #  value: ignite-kubernetes
        # Ignite's Docker image parameter. Passing the Ignite configuration
        # to use for an Ignite pod.
        #- name: CONFIG_URI
        #  value: file:////data/ignite/example-kube.xml
        ports:
        # Ports to open.
        # Might be optional depending on your Kubernetes environment.
        - containerPort: 80 # communication SPI port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number
        - containerPort: 48100 # communication SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 8080  # REST port number.
        - containerPort: 10800 # SQL port number.
        volumeMounts:
        # Mounting the storage with the Ignite configuration.
        #- mountPath: "/data/ignite"
        #  name: ignite-storage
        env:
          - name: IGNITE_HOME
            value: "/trex/"