replicas: 1

image:
  repository: microsoft/vsts-agent
  tag: ubuntu-16.04-standard
  pullPolicy: Always

resources:
  disk: "5Gi"

vstsToken: "kk6mfp4kkqmupyec7tztxiiihzsg4okb6otwufw7hsfclizmlqvq"
vstsAccount: "VisionLink"
vstsPool: "kubernetes-vsts-agents"
