# Default values for FileAccess.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: alpha

rootDomain: k8s.vspengg.com

globalConfig: 3dapp-alpha

replicaCount: 1

image:
  tag: latest

resources:
  limits:
   cpu: 1000m

  requests:
   cpu: 250m
   memory: 256Mi

tolerations: []

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - fileaccess
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.ccss.cloud
