# Common values for vlmd-preference
global:
  componentName: "vlmd-preference"
  configmap:
    s3path: s3://vss-ci-builds/VSS.MasterData.WebAPI/Preference/__Branch__/__BuildId__/db_scripts

  # Automatically have flyway perform the migration!
  flyway:
    enabled: true
  image:
    repository: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vlmd-preference
    tag: __Branch__-__BuildId__
    pullPolicy: Always
  ingress:
    enabled: true
    # Used to create an Ingress record.
    # Release automation will dynamically create hosts and target.
    hosts:
      - __ENVIRONMENT__-vlmd-preference__DOMAIN__
    annotations:
      kubernetes.io/ingress.class: nginx
      external-dns.alpha.kubernetes.io/target: __ENDPOINT__
    paths:
      - /v1
      - /v1/EventStores
      - /healthz
      - /swagger