---
version: 2

deployment:
  name: Deployment for Civil 3D - 3DP TRex Service
  source-plan: CIV3D-PRODTREX
release-naming: !include 'includes/release-naming.yaml'

environments:
  - dev
  - alpha
  - prod

dev: !include 'includes/deploy-tasks.yaml'
alpha: !include 'includes/deploy-tasks.yaml'
prod: !include 'includes/deploy-tasks.yaml'
