version: "2.1"
services:
  webapi:
    build: ./artifacts/ProjectWebApi
    env_file:
      - docker-compose-local.env
    volumes:
      - ./artifacts/logs:/app/logs
    ports:
      - "3001:80"
    depends_on:
      - schema
  mockprojectwebapi:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-mock-webapi:latest-linux
    env_file:
      - docker-compose-local.env
    ports:
      - "5001:5001"
  schema:
    build: ./database
    env_file:
      - docker-compose-local.env
    depends_on:
      - db
  db:
    image: mysql/mysql-server:5.7.15
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]
    env_file:
      - docker-compose-local.env
    ports:
      - "3306:3306"  