# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: eks.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.vspengg.com

service:
  type: ClusterIP

connectedSiteGateway:
  serviceDiscoveryName: trex-service-connectedsite
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
