# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: k8s.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: endpoints.k8s.vspengg.com

service:
  type: ClusterIP

connectedSiteGateway:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi
  environment:
    tpaasAppToken: "R1doOVJad29Wa19lT1dpUFJkSlhGZWk5YmJvYTozMndPT0VoZ2luVDdrSjY0RTVHal9ZSGVqZ1Fh"
    tpaasAuthUrl: "https://identity-stg.trimble.com/i/oauth2/token"
    connectedSiteUrl: "https://api-stg.trimble.com/t/trimble.com/cws/connectedsite/"

nodeSelector: {}

tolerations: []

affinity: {}
