apiVersion: v1
appVersion: "1.0"
description: This is a chart to delpoy all required components of a asset management 3d service into k8s. It includes webapi and masterdata consumers.
name: assetmgmt3d
version: 1.0.0
