# Default values for TagFileAuth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: alpha

rootDomain: eks.vspengg.com

globalConfig: 3dapp-alpha

# Must match the const in VSS.Common.Abstractions.ServiceDiscovery.Constants.ServiceNameConstants
serviceName: assetmgmt3d-service

replicaCount: 1

image:
  tag: latest

consumerImage:
  tag: latest

resources:
  limits:
   cpu: 1000m

  requests:
   cpu: 250m
   memory: 256Mi

tolerations: []

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - assetmgmt3d
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.vspengg.com
