# Default values for trex.
# This is a YAML-formatted file.

environment: dev

rootDomain: k8s.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: endpoints.k8s.vspengg.com

service:
  type: ClusterIP

applicationServer:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

designElevation:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

gateway:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi

immutableData:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi
  storageSize: 10Gi

mutableData:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi
  storageSize: 10Gi
  environment:
    tfaServiceBaseUrl: "http://tagfileauth.alpha.k8s.vspengg.com/"
    enableTfa: true


mutableGateway:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi

psnode:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

tileServer:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

utilities:
  replicaCount: 0
  resources: 
    requests:
      cpu: 200m
      memory: 256Mi

webtools:
  replicaCount: 1
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}
