# Default values for trex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1

psNodeReplicaCount: 1

environment: dev

rootDomain: k8s.vspengg.com

serviceAccountName: trex

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-trex"
  tag: latest

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - trex
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: endpoints.k8s.vspengg.com

service:
  type: ClusterIP

application:
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

design-elevation:
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi

gateway:
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi

immutable-data:
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

mutable-data:
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

mutable-gateway:
  resources: 
    requests:
      cpu: 300m
      memory: 512Mi

psnode:
  resources: 
    requests:
      cpu: 300m
      memory: 1.6Gi

utilities:
  resources: 
    requests:
      cpu: 200m
      memory: 256Mi

webtools:
  resources: 
    requests:
      cpu: 300m
      memory: 1Gi


nodeSelector: {}

tolerations: []

affinity: {}
