# An example of a Kubernetes configuration for Ignite pods deployment.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trex.fullname" . }}-{{ .Values.environment }}-psn
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
    component: {{ template "trex.deployname" . }}-psn
    immutable-cluster: "true"
    jmx-prometheus: "true"
spec:
  serviceName: {{ template "trex.deployname" . }}-psnode
  selector:
    matchLabels:
      #this must match one of metadata.labels above
      component: {{ template "trex.deployname" . }}-psn
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.psnode.replicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-psn
        immutable-cluster: "true"
        jmx-prometheus: "true"
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- with .Values.nodeSelector.highMemory }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations.highMemory }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.PSNode
        
        resources:
{{ toYaml .Values.psnode.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "trex.config" . }}

        #command: ["dotnet"]
        #args: ["VSS.TRex.Server.PSNode.dll"]
        command: ["dotnet"]
        args: ["VSS.TRex.Server.PSNode.dll"]

        env:
        - name: IGNITE_HOME
          value: "/trex/"
        - name: ENABLE_TFA_SERVICE
          value: "true"
        - name: TFA_SERVICE_BASEURL
          value: "http://tagfileauth.alpha.eks.ccss.cloud/"
        - name: IS_KUBERNETES
          value: "true"
        - name: DEPLOYED_ENV
          value: {{ .Values.environment }}
        - name: TREX_IGNITE_JVM_MAX_HEAP_SIZE_MB
          value: {{ .Values.psnode.javaHeapMaxSizeMb | quote  }}
        - name: TREX_IGNITE_JVM_INITIAL_HEAP_SIZE_MB
          value: {{ .Values.psnode.javaHeapInitialSizeMb | quote }}  

        ports:
        # Ports to open.
        # Might be optional depending on your Kubernetes environment.
        - containerPort: 47100 # communication SPI port number.
          name: spicoms
        - containerPort: 47500 # discovery SPI port number.
          name: spidisco
        - containerPort: 48100 # communication SPI port number.
          name: spicommsmutable
        - containerPort: 48500
          name: spidiscomutable
        - containerPort: 8080  # REST port number.
          name: restapi
        - containerPort: 10800 # SQL port number.
          name: sql
        - containerPort: 8088 #JMX prometheus
          name: jmxprometheus

        volumeMounts:
        # Mounting the persistant storage - currently this is in temp which will change when we sort config
        - mountPath: "/persist"
          name: trex-immutable-storage

  volumeClaimTemplates:
  - metadata:
      name: trex-immutable-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.psnode.storage.size }}
      storageClassName: {{ .Values.psnode.storage.className }}