{{- $name := printf "%s-%s" .Release.Name .Values.environment | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    service-name: {{ .Values.serviceName }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ $name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
