{{- $fdqn := printf "%s.%s" .Values.environment .Values.rootDomain -}}
{{- $fullName := include "TagFileGatewayservice.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "TagFileGatewayservice.name" . }}
  labels:
    app: {{ template "TagFileGatewayservice.name" . }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}.{{ $fdqn }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: 80
    {{- end -}}
