{{- $configName := printf "%s-cfg-%s" .Release.Name .Values.environment | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "TagFileGatewayservice.name" . }}
  labels:
    app: {{ template "TagFileGatewayservice.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "TagFileGatewayservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "TagFileGatewayservice.name" . }}
    spec:
      serviceAccount: {{ .Values.environment }}-service-account  
      containers:
      - image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-tagfilegateway-webapi:{{ .Values.image.tag }}
        name: {{ template "TagFileGatewayservice.name" . }}    
        resources:
{{ toYaml .Values.resources | indent 12 }}
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        - configMapRef:
            name: {{ .Values.globalConfig }}
        - secretRef:
            name: {{ .Values.globalConfig }}-secret
        imagePullPolicy: Always
        ports:
        - containerPort: 80
