# We bind the role to the Jenkins service account. The role binding is created in the namespace
# where the agents are supposed to run.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alpha-service-role-binding
  namespace: alpha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alpha-service-role
subjects:
- kind: ServiceAccount
  name: alpha-service-account
  namespace: alpha
