apiVersion: v1
kind: Secret
metadata:
  name: 3dapp-alpha-secret
  namespace: alpha
type: Opaque
data:
  TCCORG: dmxkZXY=
  TCCUSERNAME: dmxkZXY=
  TCCPWD: dmxkZXZfa2V5
  MYSQL_USERNAME: TWVyaW5v
  MYSQL_ROOT_PASSWORD: UjU4S3BlciU1