apiVersion: v1
kind: ConfigMap
metadata:
  name: 3dapp-dev
  namespace: dev
data: 
# Kubernetes Cluster Info - This must match the namespace (including case) that the pods will run in
  kubernetesNamespace: dev
# TCC configuration
  TCCBASEURL: https://www.myconnectedsite.com
  TCCFILESPACEID: u3bdc38d6-1afe-470e-8c1c-fc241d4c5e01
#Jaeger configuration
  JAEGER_AGENT_HOST: jaeger-agent.logging
  JAEGER_AGENT_PORT: "6831"
  JAEGER_SAMPLER_TYPE: const
#MySql configuration
  MYSQL_SERVER_NAME_VSPDB: rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
  MYSQL_SERVER_NAME_ReadVSPDB: rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
  MYSQL_PORT: "3306"
#Kafka configuration
  KAFKA_URI: vss-alphajson-kafka1.maas.trimblepaas.com
  KAFKA_PORT: "9092"
  KAFKA_TOPIC_NAME_SUFFIX: -Dev
  KAFKA_OFFSET: latest
  PROJECTSERVICE_KAFKA_TOPIC_NAME: VSS.Interfaces.Events.MasterData.IProjectEvent
#Service references
  ASSOCIATESUBSPROJECT_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-subscriptionservice/1.0/project/associateprojectsubscription
  CONNECTED_SITE_GATEWAY_URL: http://connectedsite.alpha.eks.vspengg.com/api/position
  COORDSYSPOST_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/1.0/coordsystem
  COORDSYSVALIDATE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/1.0/coordsystem/validation
  CUSTOMERSERVICE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-customerservice/1.0/Customers/me
  DISSOCIATESUBSPROJECT_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-subscriptionservice/1.0/project/dissociateprojectsubscription
  FILTER_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3Dfilter/1.0
  GEOFENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-geofenceservice/1.0/
  IMPORTED_FILE_API_URL2: https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/importedfile
  IMPORTED_FILE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/importedfiles
  PREFERENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-preferenceservice/1.0
  PROJECT_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/project
  PROJECT_INTERNAL_BASE_URL: http://project.dev.eks.vspengg.com
  PROJECT_SETTINGS_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4
  RAPTOR_3DPM_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0
  RAPTOR_NOTIFICATION_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0/notification
  RAPTOR_PROJECT_SETTINGS_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0
  SCHEDULER_INTERNAL_BACKGROUND_JOB_URL: http://scheduler.dev.eks.vspengg.com/internal/v1/background
  SCHEDULER_INTERNAL_BASE_URL: http://scheduler.dev.eks.vspengg.com/internal/v1
  SCHEDULER_INTERNAL_EXPORT_URL: http://scheduler.dev.eks.vspengg.com/internal/v1/export
  TILE_INTERNAL_BASE_URL: http://tile.dev.eks.vspengg.com/internal/v1
  TREX_IMPORTFILE_WRITE_API_URL: http://trex.mutable.dev.eks.vspengg.com/api/v1/design
  TREX_TAGFILE_API_URL: http://trex.mutable.dev.eks.vspengg.com/api/v2/tagfiles
  VETA_EXPORT_URL: "https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0/export/veta"
#SERVICE DISCOVERY REFERENCES
  assetdetails-public-v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/VSS-Alpha-UnifiedFleet/1.0
  assetsummary-public-v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/vss-alpha-assetutilization/1.1
  unifiedproductivity_public_v1: https://api-stg.trimble.com/t/trimble.com/vss-dev-unifiedproductivity/1.0
#TPaaS
  TPAAS_OAUTH_URL: https://identity-stg.trimble.com/i/oauth2  
#CAP configuration  
  MYSQL_CAP_DATABASE_NAME: VSS-Productivity3D-CAP-Dev
  MYSQL_CAP_TABLE_PREFIX: Project
  KAFKA_CAP_GROUP_NAME: Project-CAP
#Misc stuff   
  TILE_RENDER_MAX_ZOOM_LEVEL: "21"
  TILE_RENDER_MAX_ZOOM_RANGE: "14"
  TILE_RENDER_WAIT_INTERVAL: "2000"
  CUSTOM_INIT_SCRIPT: zookeeper_check.sh
  LOG_MAX_CHAR: "1000"
  SCHEDULER_FILTER_CLEANUP_TASK_AGE_MINUTES: "720"
  DOWNLOAD_FOLDER: C:/temp/
  ALK_KEY: 97CC5BD1CA28934796791B229AE9C3FA
  ALK_BASE_URL: http://pcmiler.alk.com/APIs/REST/v1.0/Service.svc
  AWS_TAGFILE_BUCKET_NAME: vss-stg-directtagfile-archives
  ENVIRONMENT: DEV
#AWS configuration  
  AWS_BUCKET_NAME: vss-exports-stg
  AWS_DESIGNIMPORT_BUCKET_NAME: vss-project3dp-stg
  AWS_PRESIGNED_URL_EXPIRY: 7.00:00:00
#Raptor configuration
  ASNODEIP: 10.97.96.134
  ENABLE_CONNECTED_SITE_GATEWAY: "true"
  ENABLE_RAPTOR_GATEWAY_DESIGNIMPORT: "true"
  ENABLE_RAPTOR_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_CCA_PALETTE: "false"
  ENABLE_TREX_GATEWAY_CELL_DATUM: "false"
  ENABLE_TREX_GATEWAY_DESIGNIMPORT: "false"
  ENABLE_TREX_GATEWAY_ELEVATION: "false"
  ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT: "false"
  ENABLE_TREX_GATEWAY_GRIDREPORT: "false"
  ENABLE_TREX_GATEWAY_LAYERS: "false"
  ENABLE_TREX_GATEWAY_LINEWORKFILE: "false"
  ENABLE_TREX_GATEWAY_MACHINEDESIGNS: "false"
  ENABLE_TREX_GATEWAY_MACHINES: "false"
  ENABLE_TREX_GATEWAY_PROJECTSTATISTICS: "true"
  ENABLE_TREX_GATEWAY_STATIONOFFSET: "false"
  ENABLE_TREX_GATEWAY_SURFACE: "false"
  ENABLE_TREX_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_TILES: "false"
  ENABLE_TREX_GATEWAY_VETA: "false"
  IONODEIP: 10.97.96.92
  RAPTORUSERNAME: svcRaptor
  SHAREUNC: \\dev-iolv01.vssengg.com\ProductionData
  TCCSynchOtherIssueFolder: Other... (Issue)
  TCCSynchProductionDataArchivedFolder: Production-Data (Archived)
  TCCSynchProjectBoundaryIssueFolder: Project Boundary (Issue)
  TCCSynchSubscriptionIssueFolder: Subscription (Issue)
#Cache
  MAX_FILE_SIZE: "100000000"
  TILE_CACHE_LIFE: 00:15:00
  CUSTOMER_CACHE_LIFE: 00:30:00
  ELEVATION_EXTENTS_CACHE_LIFE: 00:30:00
  FILTER_CACHE_LIFE: 00:15:00
  GEOFENCE_CACHE_LIFE: 00:00:03
  UNIFIED_PRODUCTIVITY_CACHE_LIFE: 00:00:03
  IMPORTED_FILE_CACHE_LIFE: 00:15:00
  PROJECT_CACHE_LIFE: 00:30:00
  ASSETMGMT_CACHE_LIFE: 00:30:00
  PROJECT_SETTINGS_CACHE_LIFE: 00:15:00
  TILE_RENDER_JOB_TIMEOUT: 00:00:10
  DEFAULT_CONNECTION_LIMIT: "64"
  LIBUV_THREAD_COUNT: "32"
  MAX_IO_THREADS: "1024"
  MAX_WORKER_THREADS: "512"
  MIN_IO_THREADS: "1024"
  MIN_WORKER_THREADS: "512"
  SCHEDULED_JOB_TIMEOUT: "900000"
#Notifications config
  NOTIFICATION_HUB_URL: http://push.dev.eks.vspengg.com/notifications
  PUSH_NO_AUTHENTICATION_HEADER: "true"
#DataOcean config
  DATA_OCEAN_URL: https://api-stg-usw2.trimblepaas.com/data_ocean_stage-v1.0
  DATA_OCEAN_UPLOAD_TIMEOUT_MINS: "5"
  DATA_OCEAN_UPLOAD_WAIT_MILLSECS: "1000"
  DATA_OCEAN_ROOT_FOLDER: dev
#Pegasus
  PEGASUS_DXF_PROCEDURE_ID: b8431158-1917-4d18-9f2e-e26b255900b7
  PEGASUS_EXECUTION_TIMEOUT_MINS: "10"
  PEGASUS_EXECUTION_WAIT_MILLSECS: "5000"
  PEGASUS_URL: https://api-stg-usw2.trimblepaas.com/pegasus_stage-v1.0
  SCHEDULER_ENABLE_DXF_TILE_GENERATION: "true"
#Slack
  SLACK_URL: https://hooks.slack.com/services/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
  SLACK_CHANNEL: "#notifications-dev"
  SLACK_USERNAME: vss-jobs-dev
