# This role is used to allow Jenkins scheduling of agents via Kubernetes plugin.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-service-role
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
