# We bind the role to the Jenkins service account. The role binding is created in the namespace
# where the agents are supposed to run.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-service-account