apiVersion: v1
kind: ConfigMap
metadata:
  name: 3dapp-dev
  namespace: dev
data:
  # Kubernetes Cluster Info - This must match the namespace (including case) that the pods will run in
  kubernetesNamespace: dev
  # TCC configuration
  TCCBASEURL: https://www.myconnectedsite.com
  TCCFILESPACEID: u3bdc38d6-1afe-470e-8c1c-fc241d4c5e01
  #Jaeger configuration
  #  JAEGER_AGENT_HOST: jaeger-agent.logging
  #  JAEGER_AGENT_PORT: "6831"
  #  JAEGER_SAMPLER_TYPE: const
  #MySql configuration
  MYSQL_SERVER_NAME_VSPDB: rds-rpd-mydb04.cfyg2f3omhgy.us-west-2.rds.amazonaws.com
  MYSQL_PORT: "3306"
  #Service references
  TILE_INTERNAL_BASE_URL: http://tile.dev.eks.ccss.cloud/internal/v1
  VETA_EXPORT_URL: https://api-stg.trimble.com/t/trimble.com/ccss-3d-dev-productivity/2.0/export/veta
  PREFERENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/ccss-3d-dev-preference/1.0
  #SERVICE DISCOVERY REFERENCES
  assetdetails_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/ccss-3d-alpha-UnifiedFleet/1.0
  assetsummary_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/ccss-3d-alpha-assetutilization/1.1
  cws_profilemanager_public_v1: https://api-stg.trimble.com/t/trimble.com/connectedsiteprofiles-dev/1.0
  cws_designmanager_public_v1: https://api-stg.trimble.com/t/trimble.com/cws-designmanager-dev/1.0
  cws_profilesettings_public_v1: https://api-stg.trimble.com/t/trimble.com/connectedsiteprofilesettings-dev/1.0
  tpaasemail_public_v1: https://api-stg.trimble.com/t/trimble.com/tpaas-email-service/1.0/emails/
  #TPaaS
  TPAAS_OAUTH_URL: https://identity-stg.trimble.com/i/oauth2
  #Misc stuff
  TILE_RENDER_MAX_ZOOM_LEVEL: "21"
  TILE_RENDER_MAX_ZOOM_RANGE: "14"
  TILE_RENDER_WAIT_INTERVAL: "2000"
  LOG_MAX_CHAR: "1000"
  SCHEDULER_FILTER_CLEANUP_TASK_AGE_MINUTES: "720"
  DOWNLOAD_FOLDER: C:/temp/
  ALK_KEY: 97CC5BD1CA28934796791B229AE9C3FA
  ALK_BASE_URL: http://pcmiler.alk.com/APIs/REST/v1.0/Service.svc
  ENVIRONMENT: DEV
  CORECLR_ENABLE_PROFILING: "0"
  ENABLE_ENTITLEMENTS_CHECKING: "true"
  ENTITLEMENTS_ALLOWED_EMAILS: "elspeth_jeet@trimble.com;elspeth_jeet+dev@trimble.com;karthikeyan_dakshanamurthy+dev@trimble.com;stephen_post@trimble.com;stephen_post+dev@trimble.com;david_glassenbury+dev@trimble.com;josh_nimmo@trimble.com;josh_nimmo+dev@trimble.com;kirankumar_potnuru@trimble.com"
#AWS configuration  
  AWS_DESIGNIMPORT_BUCKET_NAME: s3-pdxa-rpd-trex-designfiles
  AWS_TEMPORARY_BUCKET_NAME: s3-pdxa-rpd-workos-exports
  AWS_TAGFILE_BUCKET_NAME: s3-pdxa-rpd-tagfile-archive
  AWS_PRESIGNED_URL_EXPIRY: 7.00:00:00
  USE_LOCAL_S3_TRANSFER_PROXY_STORE: "false"
  #Raptor configuration
  ASNODEIP: 10.97.96.134
  ENABLE_CONNECTED_SITE_GATEWAY: "false"
  ENABLE_RAPTOR_GATEWAY_DESIGNIMPORT: "false"
  ENABLE_RAPTOR_GATEWAY_TAGFILE: "false"
  ENABLE_TREX_GATEWAY_CCA_PALETTE: "true"
  ENABLE_TREX_GATEWAY_CELL_DATUM: "true"
  ENABLE_TREX_GATEWAY_DESIGNIMPORT: "true"
  ENABLE_TREX_GATEWAY_EDIT_DATA: "true"
  ENABLE_TREX_GATEWAY_ELEVATION: "true"
  ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT: "true"
  ENABLE_TREX_GATEWAY_GRIDREPORT: "true"
  ENABLE_TREX_GATEWAY_LAYERS: "true"
  ENABLE_TREX_GATEWAY_LINEWORKFILE: "true"
  ENABLE_TREX_GATEWAY_MACHINEDESIGNS: "true"
  ENABLE_TREX_GATEWAY_MACHINES: "true"
  ENABLE_TREX_GATEWAY_PROJECTSTATISTICS: "true"
  ENABLE_TREX_GATEWAY_STATIONOFFSET: "true"
  ENABLE_TREX_GATEWAY_SURFACE: "true"
  ENABLE_TREX_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_TILES: "true"
  ENABLE_TREX_GATEWAY_VETA: "true"
  TREX_IS_AVAILABLE: "true"
  IONODEIP: 10.97.96.92
  RAPTORUSERNAME: svcRaptor
  SHAREUNC: \\dev-iolv01.vssengg.com\ProductionData
  TCCSynchOtherIssueFolder: Other... (Issue)
  TCCSynchProductionDataArchivedFolder: Production-Data (Archived)
  TCCSynchProjectBoundaryIssueFolder: Project Boundary (Issue)
  TCCSynchSubscriptionIssueFolder: Subscription (Issue)
  #Cache
  MAX_FILE_SIZE: "100000000"
  TILE_CACHE_LIFE: 00:15:00
  CWS_CACHE_LIFE: 00:30:00
  ELEVATION_EXTENTS_CACHE_LIFE: 00:30:00
  ENTITLEMENT_CACHE_LIFE: 00:05:00
  FILTER_CACHE_LIFE: 00:15:00
  IMPORTED_FILE_CACHE_LIFE: 00:15:00
  PROJECT_CACHE_LIFE: 00:30:00
  ASSETMGMT_CACHE_LIFE: 00:30:00
  PROJECT_SETTINGS_CACHE_LIFE: 00:15:00
  TILE_RENDER_JOB_TIMEOUT: 00:00:10
  DEFAULT_CONNECTION_LIMIT: "64"
  LIBUV_THREAD_COUNT: "32"
  MAX_IO_THREADS: "1024"
  MAX_WORKER_THREADS: "512"
  MIN_IO_THREADS: "1024"
  MIN_WORKER_THREADS: "512"
  SCHEDULED_JOB_TIMEOUT: "900000"
  #Notifications config
  NOTIFICATION_HUB_URL: http://push.dev.eks.ccss.cloud/notifications
  PUSH_NO_AUTHENTICATION_HEADER: "true"
  #DataOcean config
  DATA_OCEAN_URL: https://api-stg-usw2.trimblepaas.com/data_ocean_stage-v1.0
  DATA_OCEAN_UPLOAD_TIMEOUT_MINS: "5"
  DATA_OCEAN_UPLOAD_WAIT_MILLSECS: "1000"
  DATA_OCEAN_ROOT_FOLDER_ID: 2738140f-4dcd-429b-affb-3bd51bebaf86
  ENABLE_DATA_OCEAN: "true"
  #Pegasus
  PEGASUS_DXF_PROCEDURE_ID: 1d05aebc-37b7-4c90-8c6c-ba5d0d1c9290
  PEGASUS_GEOTIFF_PROCEDURE_ID: f61c965b-0828-40b6-8980-26c7ee164566
  PEGASUS_EXECUTION_TIMEOUT_MINS: "30"
  PEGASUS_EXECUTION_WAIT_MILLSECS: "20000"
  PEGASUS_URL: https://api-stg-usw2.trimblepaas.com/processing_stage-v1.0
  SCHEDULER_ENABLE_DXF_TILE_GENERATION: "true"
  #CWS
  MOCK_CWS_ACCOUNT: "false"
  MOCK_CWS_DESIGN: "false"
  MOCK_CWS_DEVICE: "false"
  MOCK_CWS_PROFILE: "false"
  MOCK_CWS_PROJECT: "false"
  MOCK_CWS_USER: "false"
