apiVersion: v1
kind: ConfigMap
metadata:
  name: 3dapp-dev
  namespace: dev
data: 
# Kubernetes Cluster Info - This must match the namespace (including case) that the pods will run in
  kubernetesNamespace: dev
# TCC configuration
  TCCBASEURL: https://www.myconnectedsite.com
  TCCFILESPACEID: u3bdc38d6-1afe-470e-8c1c-fc241d4c5e01
#Jaeger configuration
  JAEGER_AGENT_HOST: jaeger-agent.logging
  JAEGER_AGENT_PORT: "6831"
  JAEGER_SAMPLER_TYPE: const
#MySql configuration
  MYSQL_SERVER_NAME_VSPDB: rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
  MYSQL_SERVER_NAME_ReadVSPDB: rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
  MYSQL_PORT: "3306"
#Kafka configuration
  KAFKA_URI: kafka1.alpha.vspengg.com,kafka2.alpha.vspengg.com,kafka3.alpha.vspengg.com,kafka4.alpha.vspengg.com,kafka5.alpha.vspengg.com
  KAFKA_PORT: "9092"
  KAFKA_TOPIC_NAME_SUFFIX: -Dev
  KAFKA_OFFSET: latest
  PROJECTSERVICE_KAFKA_TOPIC_NAME: VSS.Interfaces.Events.MasterData.IProjectEvent
#Service references
  ASSOCIATESUBSPROJECT_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-subscriptionservice/1.0/project/associateprojectsubscription
  CUSTOMERSERVICE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-customerservice/1.0/Customers/me
  DISSOCIATESUBSPROJECT_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-dev-subscriptionservice/1.0/project/dissociateprojectsubscription
  GEOFENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-geofenceservice/1.0/  
  PREFERENCE_API_URL: https://api-stg.trimble.com/t/trimble.com/vss-alpha-preferenceservice/1.0 
  TILE_INTERNAL_BASE_URL: http://tile.dev.eks.vspengg.com/internal/v1
  VETA_EXPORT_URL: "https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0/export/veta"
#SERVICE DISCOVERY REFERENCES
  assetdetails_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/VSS-Alpha-UnifiedFleet/1.0
  assetsummary_public_v1: https://alpha1ufl.myvisionlink.com/t/trimble.com/vss-alpha-assetutilization/1.1
  unifiedproductivity_public_v1: https://api-stg.trimble.com/t/trimble.com/vss-dev-unifiedproductivity/1.0
  productivity3d_service_public_v1: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/1.0
  productivity3d_service_public_v2: https://api-stg.trimble.com/t/trimble.com/vss-dev-3dproductivity/2.0
  productivity3dinternal_service_public_v2: http://10.97.99.166:5001
  tpaasemail_public_v1: https://api-stg.trimble.com/t/trimble.com/tpaas-email-service/1.0/emails/
  cws_profilemanager_public_v1: https://api-stg.trimble.com/t/trimble.com/cws-profilemanager-stg/1.0
  cws_devicemanager_public_v2: https://api-stg.trimble.com/t/trimble.com/cws-devicemanager-stg/2.0
#TPaaS
  TPAAS_OAUTH_URL: https://identity-stg.trimble.com/i/oauth2 
  INTERNAL_JWT: eyJ4NXQiOiJNREk0WTJNd1pUVmpNRGRsTkdVeFlUSmtaV00zWmpCaVptVTBZVFprTkRjek9HTmhZMk5oTmciLCJraWQiOiJNREk0WTJNd1pUVmpNRGRsTkdVeFlUSmtaV00zWmpCaVptVTBZVFprTkRjek9HTmhZMk5oTmciLCJhbGciOiJSUzI1NiJ9.eyJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hY2NvdW50TG9ja2VkIjoiZmFsc2UiLCJzdWIiOiJmMzFmYmFmMC0xMzBjLTQzM2ItYjlhMC03YWQ3NWI4M2Y0MmEiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hY2NvdW50bmFtZSI6InRyaW1ibGUuY29tIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvcm9sZSI6IiIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2ZhaWxlZExvZ2luQXR0ZW1wdHMiOiIwIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb250aWVyIjoiVW5saW1pdGVkIiwiaXNzIjoiaHR0cHM6XC9cL2lkZW50aXR5LnRyaW1ibGUuY29tIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvbGFzdFB3ZFNldFRpbWVTdGFtcCI6IjE1MjY0NjMyMTAwOTIiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9lbmR1c2VyVGVuYW50SWQiOjEsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2xhc3RMb2dpblRpbWVTdGFtcCI6IjE1NDA3NTQ4MjUwOTkiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC91dWlkIjoiZjMxZmJhZjAtMTMwYy00MzNiLWI5YTAtN2FkNzViODNmNDJhIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvdXNlckNyZWF0ZVRpbWVTdGFtcCI6IjE1MjY0NjMyMTAwOTIiLCJhenAiOiI5WDd6MkZKNXRBUVNNd05KVXhPaGZCcVVWTmdhIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZW1haWxhZGRyZXNzIjoiY3RjdC10cGFhcy11Z0B0cmltYmxlLmNvbSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2xhc3RuYW1lIjoiZGV2IiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZmlyc3RuYW1lIjoiY3RjdCIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL3VzZXJ0eXBlIjoiQVBQTElDQVRJT04iLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hcHBsaWNhdGlvbmlkIjowLCJleHAiOjE1Njk1NTM4ODAsImlhdCI6MTU2OTU0OTk0MSwiaHR0cDpcL1wvdHJpbWJsZS5jb21cL3RwYWFzXC9jbGFpbXNcL2FwcGxpY2F0aW9ubmFtZSI6IlByb2QtRWFydGh3b3Jrcy1FQzUyMCIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2FwaWNvbnRleHQiOiJcL3RcL3RyaW1ibGUuY29tXC92c3MtM2Rwcm9kdWN0aXZpdHkiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9wYXNzd29yZFRpbWVzdGFtcCI6IjE1MjY0NjMyMTAwOTIiLCJodHRwOlwvXC90cmltYmxlLmNvbVwvdHBhYXNcL2NsYWltc1wvdXNlcm5hbWUiOiJjdGN0LXRwYWFzLXVnQHRyaW1ibGUuY29tIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvdmVyc2lvbiI6IjIuMCIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2tleXR5cGUiOiJQUk9EVUNUSU9OIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb25uYW1lIjoiUHJvZC1FYXJ0aHdvcmtzLUVDNTIwIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvZW5kdXNlciI6ImN0Y3QtdHBhYXMtdWdAdHJpbWJsZS5jb20iLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9sYXN0VXBkYXRlVGltZVN0YW1wIjoiMTU2Njg1NjI2ODUzNiIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2dpdmVubmFtZSI6ImN0Y3QiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9lbWFpbFZlcmlmaWVkIjoidHJ1ZSIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2FjY291bnR1c2VybmFtZSI6ImN0Y3QtdHBhYXMtdWciLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC90aWVyIjoiVW5saW1pdGVkIiwiaHR0cDpcL1wvdHJpbWJsZS5jb21cL3RwYWFzXC9jbGFpbXNcL2FwcGxpY2F0aW9uaWQiOiJhNWI4ODllOS04ODdjLTQ0NWItOTlhOS0wZDQ3NjZlODEwMjUiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9zdWJqZWN0IjoiY3RjdC10cGFhcy11ZyIsInNjb3BlcyI6IkRJRF8wOGQ2YWM4Ni0wY2I3LTdjNWQtY2EyYi0yYjAwMDEwMDA1NmQiLCJodHRwOlwvXC90cmltYmxlLmNvbVwvdHBhYXNcL2NsYWltc1wvY29uc3VtZXJrZXkiOiI5WDd6MkZKNXRBUVNNd05KVXhPaGZCcVVWTmdhIn0.DnhJONdd3NGygZwcwk7eO2w-awVhHjffzMAUUPdROGQ4WMuXaZoGBSAI1p7GtJM5Zq_hjs24Of3rVQ5yKQsFO6q6g4ghgjYSCIhmYf3b6VsygZvtlVMPYbzO7Xxkodu3iErs8Tmka-WEiy3u3I2jDUn0x5v-ypmemJoeqHGCi0s
#CAP configuration  
  MYSQL_CAP_DATABASE_NAME: VSS-Productivity3D-CAP-Dev
  MYSQL_CAP_TABLE_PREFIX: Project
  KAFKA_CAP_GROUP_NAME: Project-CAP
#Misc stuff   
  TILE_RENDER_MAX_ZOOM_LEVEL: "21"
  TILE_RENDER_MAX_ZOOM_RANGE: "14"
  TILE_RENDER_WAIT_INTERVAL: "2000"
  CUSTOM_INIT_SCRIPT: zookeeper_check.sh
  LOG_MAX_CHAR: "1000"
  SCHEDULER_FILTER_CLEANUP_TASK_AGE_MINUTES: "720"
  DOWNLOAD_FOLDER: C:/temp/
  ALK_KEY: 97CC5BD1CA28934796791B229AE9C3FA
  ALK_BASE_URL: http://pcmiler.alk.com/APIs/REST/v1.0/Service.svc
  AWS_TAGFILE_BUCKET_NAME: vss-stg-directtagfile-archives
  ENVIRONMENT: DEV
  CORECLR_ENABLE_PROFILING: "0"
#AWS configuration  
  AWS_BUCKET_NAME: vss-exports-stg
  AWS_DESIGNIMPORT_BUCKET_NAME: vss-project3dp-stg
  AWS_PRESIGNED_URL_EXPIRY: 7.00:00:00
#Raptor configuration
  ASNODEIP: 10.97.96.134
  ENABLE_CONNECTED_SITE_GATEWAY: "true"
  ENABLE_RAPTOR_GATEWAY_DESIGNIMPORT: "true"
  ENABLE_RAPTOR_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_CCA_PALETTE: "false"
  ENABLE_TREX_GATEWAY_CELL_DATUM: "false"
  ENABLE_TREX_GATEWAY_DESIGNIMPORT: "false"
  ENABLE_TREX_GATEWAY_EDIT_DATA: "false"
  ENABLE_TREX_GATEWAY_ELEVATION: "false"
  ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT: "false"
  ENABLE_TREX_GATEWAY_GRIDREPORT: "false"
  ENABLE_TREX_GATEWAY_LAYERS: "false"
  ENABLE_TREX_GATEWAY_LINEWORKFILE: "false"
  ENABLE_TREX_GATEWAY_MACHINEDESIGNS: "false"
  ENABLE_TREX_GATEWAY_MACHINES: "false"
  ENABLE_TREX_GATEWAY_PROJECTSTATISTICS: "true"
  ENABLE_TREX_GATEWAY_STATIONOFFSET: "false"
  ENABLE_TREX_GATEWAY_SURFACE: "false"
  ENABLE_TREX_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_TILES: "false"
  ENABLE_TREX_GATEWAY_VETA: "false"
  IONODEIP: 10.97.96.92
  RAPTORUSERNAME: svcRaptor
  SHAREUNC: \\dev-iolv01.vssengg.com\ProductionData
  TCCSynchOtherIssueFolder: Other... (Issue)
  TCCSynchProductionDataArchivedFolder: Production-Data (Archived)
  TCCSynchProjectBoundaryIssueFolder: Project Boundary (Issue)
  TCCSynchSubscriptionIssueFolder: Subscription (Issue)
#Cache
  MAX_FILE_SIZE: "100000000"
  TILE_CACHE_LIFE: 00:15:00
  CUSTOMER_CACHE_LIFE: 00:30:00
  ELEVATION_EXTENTS_CACHE_LIFE: 00:30:00
  FILTER_CACHE_LIFE: 00:15:00
  GEOFENCE_CACHE_LIFE: 00:00:03
  UNIFIED_PRODUCTIVITY_CACHE_LIFE: 00:00:03
  IMPORTED_FILE_CACHE_LIFE: 00:15:00
  PROJECT_CACHE_LIFE: 00:30:00
  ASSETMGMT_CACHE_LIFE: 00:30:00
  PROJECT_SETTINGS_CACHE_LIFE: 00:15:00
  TILE_RENDER_JOB_TIMEOUT: 00:00:10
  DEFAULT_CONNECTION_LIMIT: "64"
  LIBUV_THREAD_COUNT: "32"
  MAX_IO_THREADS: "1024"
  MAX_WORKER_THREADS: "512"
  MIN_IO_THREADS: "1024"
  MIN_WORKER_THREADS: "512"
  SCHEDULED_JOB_TIMEOUT: "900000"
#Notifications config
  NOTIFICATION_HUB_URL: http://push.dev.eks.vspengg.com/notifications
  PUSH_NO_AUTHENTICATION_HEADER: "true"
#DataOcean config
  DATA_OCEAN_URL: https://api-stg-usw2.trimblepaas.com/data_ocean_stage-v1.0
  DATA_OCEAN_UPLOAD_TIMEOUT_MINS: "5"
  DATA_OCEAN_UPLOAD_WAIT_MILLSECS: "1000"
  DATA_OCEAN_ROOT_FOLDER_ID: a3f51fdf-69e4-4d80-b734-e72e4f9b36d9
  ENABLE_DATA_OCEAN: "true"
#Pegasus
  PEGASUS_DXF_PROCEDURE_ID: 1d05aebc-37b7-4c90-8c6c-ba5d0d1c9290
  PEGASUS_GEOTIFF_PROCEDURE_ID: f61c965b-0828-40b6-8980-26c7ee164566
  PEGASUS_EXECUTION_TIMEOUT_MINS: "30"
  PEGASUS_EXECUTION_WAIT_MILLSECS: "20000"
  PEGASUS_URL: https://api-stg-usw2.trimblepaas.com/pegasus_stage-v1.0
  SCHEDULER_ENABLE_DXF_TILE_GENERATION: "true"
#Slack
  SLACK_URL: https://hooks.slack.com/services/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
  SLACK_CHANNEL: "#notifications-dev"
  SLACK_USERNAME: vss-jobs-dev
