apiVersion: v1
kind: ConfigMap
metadata:
  name: 3dapp-prod
  namespace: prod
data:
  # Kubernetes Cluster Info - This must match the namespace (including case) that the pods will run in
  kubernetesNamespace: prod
  # TCC configuration
  TCCBASEURL: https://www.myconnectedsite.com
  TCCFILESPACEID: ucc083712-346e-466e-8cba-3c3eb0f9fb05
  TCC_TAGFILE_FILESPACEID: ufb92e643-ca3e-49b3-a52f-0fbf29c3e18e
  TCCUSERNAME: vlproduction
  TCCPWD: vlproduction_key5
  TCCORG: vlproduction
  #Jaeger configuration
  #JAEGER_AGENT_HOST: jaeger-agent.logging
  #JAEGER_AGENT_PORT: "6831"
  #JAEGER_SAMPLER_TYPE: const
#MySql configuration
  MYSQL_SERVER_NAME_VSPDB: rds-csp-mydb01.custtyfqh3uu.us-west-2.rds.amazonaws.com
  MYSQL_SERVER_NAME_ReadVSPDB: rds-csp-mydb01.custtyfqh3uu.us-west-2.rds.amazonaws.com
  MYSQL_PORT: "3306"
#Service references
  cws_profilemanager_public_v1: https://api.trimble.com/t/trimble.com/cws-profilemanager/1.0
  cws_designmanager_public_v1: https://api.trimble.com/t/trimble.com/cws-designmanager/1.0
  cws_profilesettings_public_v1: https://api.trimble.com/t/trimble.com/cws-profilesettings/1.0
  cws_devicegateway_public_v2: https://api.trimble.com/t/trimble.com/cws-devicegateway/2.0
  PREFERENCE_API_URL: https://api.trimble.com/t/trimble.com/ccss-worksos-preference/1.0
  TILE_BASE_URL: http://tile.prod.ccss.eks/internal/v1
#SERVICE DISCOVERY REFERENCES
  assetdetails_public_v1: https://unifiedfleet.myvisionlink.com/t/trimble.com/vss-unifiedfleet/1.0
  assetsummary_public_v1: https://unifiedfleet.myvisionlink.com/t/trimble.com/vss-assetutilization/1.1
#TPaaS
  TPAAS_OAUTH_URL: https://identity.trimble.com/i/oauth2
#Misc stuff
  TILE_RENDER_MAX_ZOOM_LEVEL: "21"
  TILE_RENDER_MAX_ZOOM_RANGE: "14"
  TILE_RENDER_WAIT_INTERVAL: "2000"
  LOG_MAX_CHAR: "1000"
  SCHEDULER_FILTER_CLEANUP_TASK_AGE_MINUTES: "720"
  DOWNLOAD_FOLDER: C:/temp/
  ALK_KEY: 97CC5BD1CA28934796791B229AE9C3FA
  ALK_BASE_URL: http://pcmiler.alk.com/APIs/REST/v1.0/Service.svc
  ENVIRONMENT: PROD
  CORECLR_ENABLE_PROFILING: "0"
  ENABLE_ENTITLEMENTS_CHECKING: "true"
  ENABLE_ENTITLEMENTS_SERVICE_CHECKING: "false"
  ENTITLEMENTS_ALLOWED_EMAILS: "stephen_benko@trimble.com;jeff_gibson@trimble.com;patrick_stevenson@trimble.com;mark_schwartz@trimble.com;simon_waterhouse@trimble.com;chinkit_trivedi@trimble.com;dan_hamilton@trimble.com;stefan_argiriu@trimble.com;michael_carris@trimble.com;scott_bridges@trimble.com;nick_fifarek@trimble.com;anthony_gosden@trimble.com;dwayne_rosie@trimble.com;will_newall@trimble.com;carlos_ramirezortiz@trimble.com;barret_chapman@trimble.com;dmitry_golovachev@trimble.com;stephen_post+prod@trimble.com;josh_nimmo@trimble.com;leo_haughton@trimble.com;raymond_wilson@trimble.com;elspeth_jeet@trimble.com;jeannie_may@trimble.com;aaron_morgan@trimble.com;david_glassenbury@trimble.com;anatoli_kozoub@trimble.com;alan_rose@trimble.com;grant_higgins@trimble.com;caelan_barr@trimble.com"
#AWS configuration  
  # This is used for Tag File Gateway
  AWS_ALL_TAGFILE_BUCKET_NAME: s3-pdxa-csp-tagarchive
  # This is used for Data model Archive
  AWS_TAGFILE_BUCKET_NAME: s3-pdxa-csp-trex-dm-archive
  AWS_DESIGNIMPORT_BUCKET_NAME: s3-pdxa-csp-trex-files
  AWS_TEMPORARY_BUCKET_NAME: s3-pdxa-csp-export
  AWS_PRESIGNED_URL_EXPIRY: 7.00:00:00
  USE_LOCAL_S3_TRANSFER_PROXY_STORE: "false"
#Raptor configuration
  ENABLE_CONNECTED_SITE_GATEWAY: "false"
  ENABLE_RAPTOR_GATEWAY_DESIGNIMPORT: "false"
  ENABLE_RAPTOR_GATEWAY_TAGFILE: "false"
  ENABLE_TREX_GATEWAY_CCA_PALETTE: "true"
  ENABLE_TREX_GATEWAY_CELL_DATUM: "true"
  ENABLE_TREX_GATEWAY_DESIGNIMPORT: "true"
  ENABLE_TREX_GATEWAY_EDIT_DATA: "true"
  ENABLE_TREX_GATEWAY_ELEVATION: "true"
  ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT: "true"
  ENABLE_TREX_GATEWAY_GRIDREPORT: "true"
  ENABLE_TREX_GATEWAY_LAYERS: "true"
  ENABLE_TREX_GATEWAY_LINEWORKFILE: "true"
  ENABLE_TREX_GATEWAY_MACHINEDESIGNS: "true"
  ENABLE_TREX_GATEWAY_MACHINES: "true"
  ENABLE_TREX_GATEWAY_PROJECTSTATISTICS: "true"
  ENABLE_TREX_GATEWAY_STATIONOFFSET: "true"
  ENABLE_TREX_GATEWAY_SURFACE: "true"
  ENABLE_TREX_GATEWAY_TAGFILE: "true"
  ENABLE_TREX_GATEWAY_TILES: "true"
  ENABLE_TREX_GATEWAY_VETA: "true"
  TREX_IS_AVAILABLE: "true"
  ASNODEIP: 10.97.96.150
  IONODEIP: 10.97.96.165
  RAPTORUSERNAME: svcRaptor
  SHAREUNC: \\prod-iolv01.vssengg.com\ProductionData
  TCCSynchOtherIssueFolder: Other... (Issue)
  TCCSynchProductionDataArchivedFolder: Production-Data (Archived)
  TCCSynchProjectBoundaryIssueFolder: Project Boundary (Issue)
  TCCSynchSubscriptionIssueFolder: Subscription (Issue)
#Cache
  MAX_FILE_SIZE: "100000000"
  TILE_CACHE_LIFE: 00:15:00
  CWS_CACHE_LIFE: 00:30:00
  ELEVATION_EXTENTS_CACHE_LIFE: 00:30:00
  ENTITLEMENT_CACHE_LIFE: 00:05:00
  FILTER_CACHE_LIFE: 00:15:00
  IMPORTED_FILE_CACHE_LIFE: 00:15:00
  PROJECT_CACHE_LIFE: 00:30:00
  ASSETMGMT_CACHE_LIFE: 00:30:00
  PROJECT_SETTINGS_CACHE_LIFE: 00:15:00
  TILE_RENDER_JOB_TIMEOUT: 00:00:10  
  DEFAULT_CONNECTION_LIMIT: "64"
  LIBUV_THREAD_COUNT: "32"
  MAX_IO_THREADS: "1024"
  MAX_WORKER_THREADS: "512"
  MIN_IO_THREADS: "1024"
  MIN_WORKER_THREADS: "512"
  SCHEDULED_JOB_TIMEOUT: "900000"
#Notifications
  NOTIFICATION_HUB_URL: http://push.prod.ccss.eks/notifications
  PUSH_NO_AUTHENTICATION_HEADER: "true" 
#DataOcean
  DATA_OCEAN_URL: https://api-usw2.trimblepaas.com/data_ocean-v1.0
  DATA_OCEAN_UPLOAD_TIMEOUT_MINS: "5"
  DATA_OCEAN_UPLOAD_WAIT_MILLSECS: "1000"
  DATA_OCEAN_ROOT_FOLDER_ID: a2ea592c-0e77-43aa-b041-8b542a0a9cb4
  ENABLE_DATA_OCEAN: "true"
#Pegasus
  PEGASUS_DXF_PROCEDURE_ID: cd1ef2a0-63fb-4469-809a-e650c4feb4ca
  PEGASUS_GEOTIFF_PROCEDURE_ID: f61c965b-0828-40b6-8980-26c7ee164566
  PEGASUS_EXECUTION_TIMEOUT_MINS: "30"
  PEGASUS_EXECUTION_WAIT_MILLSECS: "20000"
  PEGASUS_URL: https://api-usw2.trimblepaas.com/processing-v1.0
  SCHEDULER_ENABLE_DXF_TILE_GENERATION: "true"
  #CWS
  MOCK_CWS_ACCOUNT: "false"
  MOCK_CWS_DESIGN: "false"
  MOCK_CWS_DEVICE: "false"
  MOCK_CWS_PROFILE: "false"
  MOCK_CWS_PROJECT: "false"
  MOCK_CWS_USER: "false"
