# An example of a Kubernetes configuration for Ignite pods deployment.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "trex.deployname" . }}-mds
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
    component: {{ template "trex.deployname" . }}-mds
    mutable-cluster: "true"
    immutable-cluster: "true"
    jmx-prometheus: "true"
spec:
  serviceName: {{ template "trex.deployname" . }}-mutable-data
  selector:
    matchLabels:
      #this must match one of metadata.labels above
      component: {{ template "trex.deployname" . }}-mds
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.mutableData.replicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-mds
        mutable-cluster: "true"
        immutable-cluster: "true"
        jmx-prometheus: "true"
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ .Values.serviceAccountName }}

{{ if .Values.nodeSelector.enabled }}
{{- with .Values.nodeSelector.generalPurpose }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}

{{ if .Values.tolerations.enabled }}
{{- with .Values.tolerations.generalPurpose }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}

      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.MutableData
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        resources:
{{ toYaml .Values.mutableData.resources | indent 10 }}

        envFrom:
        - configMapRef:
            name: {{ template "trex.config" . }}
        command: ["dotnet"]
        args: ["VSS.TRex.Server.MutableData.dll"]

        env:
        - name: IGNITE_HOME
          value: "/trex/"
        - name: ENABLE_TFA_SERVICE
          value: {{ .Values.mutableData.environment.enableTfa | quote }}
        - name: ENABLE_DEVICE_GATEWAY
          value: {{ .Values.mutableData.environment.enableDeviceGateway | quote }}
        - name: IS_KUBERNETES
          value: "true"
        - name: DEPLOYED_ENV
          value: {{ .Values.environment }}
        - name: ENABLE_TAGFILE_ARCHIVING
          value: {{ .Values.mutableData.environment.enableTagFileArchiving | quote }}
        - name: ENABLE_TAGFILE_ARCHIVING_METADATA
          value: {{ .Values.mutableData.environment.enableTagFileArchivingMetadata | quote }}
        - name: MIN_TAGFile_LENGTH
          value: {{ .Values.mutableData.environment.minTagFileLength | quote }}
        - name: TAGFILE_ARCHIVE_FOLDER
          value: {{ .Values.mutableData.environment.tagfileArchiveFolder }}
        - name: TREX_IGNITE_JVM_MAX_HEAP_SIZE_MB
          value: {{ .Values.mutableData.javaHeapMaxSizeMb | quote }}
        - name: TREX_IGNITE_JVM_INITIAL_HEAP_SIZE_MB
          value: {{ .Values.mutableData.javaHeapInitialSizeMb | quote }}  

        ports:
{{ toYaml .Values.trexPorts | indent 8 }}


{{ if .Values.mutableData.storage.enabled }}
        volumeMounts:
        # Mounting the persistant storage - currently this is in temp which will change when we sort config
        - mountPath: "/persist/"
          name: trex-mutable-storage
{{ end }}

{{ if .Values.mutableData.storage.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: trex-mutable-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mutableData.storage.size }}
      storageClassName: {{ .Values.mutableData.storage.className }}
{{ end }}