version: '3'
services:
  webapi_dev:
    image: 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-raptor-webapi:[VERSION]
    environment:
      - ALK_KEY=97CC5BD1CA28934796791B229AE9C3FA
      - ASNODEIP=dev-aslv01.vssengg.com
      - AWS_ACCESS_KEY=AKIAIBGOEETXHMANDX7A
      - AWS_PRESIGNED_URL_EXPIRY=7.00:00:00
      - AWS_SECRET_KEY=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
      - AWS_TAGFILE_BUCKET_NAME=vss-stg-directtagfile-archives
      - AWS_DESIGNIMPORT_BUCKET_NAME=vss-project3dp-stg
      - CONNECTED_SITE_GATEWAY_URL=http://connectedsite.alpha.eks.vspengg.com/api/status
      - CUSTOMERSERVICE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-customerservice/1.0/Customers/me
      - CUSTOMER_CACHE_LIFE=00:30:00
      - DEFAULT_CONNECTION_LIMIT=64
      - ELEVATION_EXTENTS_CACHE_LIFE=00:30:00
      - ENABLE_CONNECTED_SITE_GATEWAY=false
      - ENABLE_RAPTOR_GATEWAY_TAGFILE=true
      - ENABLE_TREX_GATEWAY_LINEWORKFILE=false
      - ENABLE_TREX_GATEWAY_TAGFILE=false
      - ENABLE_TREX_GATEWAY_STATIONOFFSET=false
      - ENABLE_TREX_GATEWAY_GRIDREPORT=false
      - ENABLE_TREX_GATEWAY_DESIGN_BOUNDARY=false
      - ENABLE_TREX_GATEWAY_SURFACE=false
      - ENABLE_TREX_GATEWAY_VETA=false
      - ENABLE_TREX_GATEWAY_EXPORT_PASSCOUNT=false
      - FILTER_API_URL=http://filter.dev.eks.vspengg.com/api/v1
      - FILTER_CACHE_LIFE=00:15:00
      - GEOFENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-geofenceservice/1.0
      - GEOFENCE_CACHE_LIFE=00:15:00
      - IMPORTED_FILE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/importedfiles
      - IMPORTED_FILE_CACHE_LIFE=00:15:00
      - IONODEIP=dev-iolv01.vssengg.com
      - LIBUV_THREAD_COUNT=32
      - LOG_MAX_CHAR=1000
      - MAX_IO_THREADS=1024
      - MAX_WORKER_THREADS=512
      - MIN_IO_THREADS=1024
      - MIN_WORKER_THREADS=512
      - PREFERENCE_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-alpha-preferenceservice/1.0
      - PROJECT_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4/project
      - PROJECT_CACHE_LIFE=00:30:00
      - ASSETMGMT_CACHE_LIFE=00:15:00
      - PROJECT_SETTINGS_API_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-projects/1.4
      - PROJECT_SETTINGS_CACHE_LIFE=00:15:00
      - SCHEDULED_JOB_TIMEOUT=900000
      - SCHEDULER_INTERNAL_EXPORT_URL=http://scheduler.dev.eks.vspengg.com/internal/v1/export
      - SHAREUNC=\\dev-iolv01.vssengg.com\ProductionData
      - SNAKEPIT_HOST=snakepit.dev.eks.vspengg.com
      - TCCBASEURL=https://www.myconnectedsite.com
      - TCCFILESPACEID=u3bdc38d6-1afe-470e-8c1c-fc241d4c5e01
      - TCCFILESPACENAME=vldatastore-dev
      - TCCORG=vldev
      - TCCPWD=vldev_key
      - TCCSynchOtherIssueFolder=Other... (Issue)
      - TCCSynchProductionDataArchivedFolder=Production-Data (Archived)
      - TCCSynchProjectBoundaryIssueFolder=Project Boundary (Issue)
      - TCCSynchSubscriptionIssueFolder=Subscription (Issue)
      - TCCUSERNAME=vldev
      - TILE_RENDER_JOB_TIMEOUT=00:00:10
      - TILE_RENDER_MAX_ZOOM_LEVEL=21
      - TILE_RENDER_MAX_ZOOM_RANGE=14
      - TILE_RENDER_WAIT_INTERVAL=2000
      - TREX_TAGFILE_API_URL=http://trex.mutable.dev.eks.vspengg.com/api/v2/tagfiles
      - RAPTORUSERNAME=svcRaptor
      - MYSQL_SERVER_NAME_VSPDB=rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=Merino
      - MYSQL_ROOT_PASSWORD="R58Kper%5"
      - MYSQL_USERNAME_BUILD="vssBuildUsr"
      - MYSQL_PASSWORD_BUILD="V$$8u1ld45er"
      - MYSQL_CAP_DATABASE_NAME=VSS-Productivity3D-CAP-Dev,
      - MYSQL_CAP_TABLE_PREFIX=3dpm,
      - KAFKA_URI=10.97.97.32
      - KAFKA_PORT=9092
      - KAFKA_CAP_GROUP_NAME=3dpm-CAP,
      - KAFKA_TOPIC_NAME_SUFFIX=-Dev
      - TILE_BASE_URL=https://api-stg.trimble.com/t/trimble.com/vss-dev-tile/1.0
      - NOTIFICATION_HUB_URL=http://push.dev.eks.vspengg.com/notifications
      - PUSH_NO_AUTHENTICATION_HEADER=true
    ports:
     - "5001:80"
    restart: always
networks:
  default:
    external:
      name: nat
 