# Default values for projectservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: alpha

rootDomain: k8s.vspengg.com

globalConfig: 3dapp-alpha

replicaCount: 1

image:
  repository: "276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-3dpm-webapi"
  tag: latest-linux

resources:
  limits:
   cpu: 1000m

  requests:
   cpu: 250m
   memory: 256Mi

tolerations: []

ingress:
  enabled: true
  # Used to create an Ingress record. environment name will be appended
  hosts:
    - 3dpm
  annotations:
    kubernetes.io/ingress.class: nginx
    external-dns.alpha.kubernetes.io/target: eks.vspengg.com
