# An example of a Kubernetes configuration for Ignite pods deployment.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trex.deployname" . }}-project-rebuilder
  labels:
    app: {{ template "trex.deployname" . }}
    component: {{ template "trex.deployname" . }}-project-rebuilder
    chart: {{ template "trex.chart" . }}
    immutable-cluster: "true"
    jmx-prometheus: "true"
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.projectRebuilderServer.replicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-project-rebuilder
        immutable-cluster: "true"
        jmx-prometheus: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- with .Values.nodeSelector.none }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations.none }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.ProjectRebuilder

        resources:
{{ toYaml .Values.projectRebuilderServer.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "trex.config" . }}
            
        command: ["dotnet"]
        args: ["VSS.TRex.Server.ProjectRebuilder.dll"]

        ports:
        # Ports to open.
        # Might be optional depending on your Kubernetes environment.
        - containerPort: 47100 # communication SPI port number.
          name: spicoms
        - containerPort: 47500 # discovery SPI port number.
          name: spidisco
        - containerPort: 48100 # communication SPI port number.
          name: spicommsmutable
        - containerPort: 48500
          name: spidiscomutable
        - containerPort: 8088 #JMX prometheus
          name: jmxprometheus
        - containerPort: 8080  # REST port number.
          name: restapi
        - containerPort: 10800 # SQL port number.
          name: sql
        env:
          - name: IGNITE_HOME
            value: "/trex/"
          - name: IS_KUBERNETES
            value: "true"
          - name: DEPLOYED_ENV
            value: {{ .Values.environment }}
          - name: TREX_IGNITE_JVM_MAX_HEAP_SIZE_MB
            value: {{ .Values.projectRebuilderServer.javaHeapMaxSizeMb | quote }}
          - name: TREX_IGNITE_JVM_INITIAL_HEAP_SIZE_MB
            value: {{ .Values.projectRebuilderServer.javaHeapInitialSizeMb | quote }}  
