---
version: 2
triggers: !include 'includes/build-triggers.yaml'
plan:
  project-key: CIV3D
  name: asset-maangement-webapi
  key: ASSET

variables:
  jenkins_username: jnimmo2
  jenkins_token: 1123a83c8b6925f1567370f72074adf77f
  jenkins_url: http://ci.eks.ccss.cloud
  service: asset-management-webapi
  service_path: src/service/3dAssetMgmt
  image_tag: 'None'
  build_db: false
  run_acceptance_tests: false
  run_unit_tests: false


stages:
  - Build:
      jobs: 
        - Build Jenkins

Build Jenkins: !include 'build-jenkins.yaml'

