---
version: 2
plan:
  project-key: CIV3D
  name: productivity3d-raptor-webapi
  key: PRODRAPTOR

triggers: !include 'includes/build-triggers.yaml'
#branches: !include 'includes/build-branches.yaml'

variables:
  jenkins_username: jnimmo2
  jenkins_token: 1123a83c8b6925f1567370f72074adf77f
  jenkins_url: http://ci.eks.ccss.cloud
  service_discovery_name: productivity3d-raptor-service
  service: tile-webapi
  service_path: src/service/Filter
  test: something

stages:
  - Build:
      jobs: 
        - Build Jenkins

Build Jenkins: 
  tasks: !include 'includes/jenkins-build.yaml'
  artifacts: !include 'includes/jenkins-artifacts.yaml'
  final-tasks: !include 'includes/jenkins-test-coverage.yaml'

