---
version: 2
plan:
  project-key: CIV3D
  name: project-webapi
  key: PROJECT

triggers: !include 'includes/build-triggers.yaml'
#branches: !include 'includes/build-branches.yaml'

variables:
  jenkins_username: jnimmo2
  jenkins_token: 1123a83c8b6925f1567370f72074adf77f
  jenkins_url: http://ci.eks.ccss.cloud
  service: project-webapi
  service_path: src/service/Project
  service_discovery_name: project-service
  image_tag: 'None'
  build_db: true
  run_acceptance_tests: true
  run_unit_tests: true

stages:
  - Build:
      jobs: 
        - Build Jenkins

Build Jenkins: 
  tasks: !include 'includes/jenkins-build.yaml'
  artifacts: !include 'includes/jenkins-artifacts.yaml'
  final-tasks: !include 'includes/jenkins-test-coverage.yaml'


