version: '2'
services:
  webapi:
    build: ./artifacts/WebApi
    env_file:
     - docker-compose.env
    volumes:
      - ./artifacts/logs:/app/logs 
    depends_on:
      - schema
  accepttest:
    build: ./AcceptanceTests/deploy
    env_file:
     - docker-compose.env
    volumes:
      - ./AcceptanceTests/deploy/testresults:/app/testresults
    depends_on:
      - webapi
      - masterdataconsumerasset
      - kafka
      