version: '3'
services:
  schema:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-masterdataconsumer-db:latest-release-[MVERSION]    
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    environment:
  webapi:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-tagfileauth-webapi:latest-release-[WVERSION]
    ports:
      - 6001:80
    deploy:
      replicas: 1
    environment:
