version: '3'
services:  
  webapi:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/vss-tagfileauth-webapi:latest-release-[WVERSION]
    ports:
      - 6001:80
    deploy:
      replicas: 1
    environment:
     - MYSQL_SERVER_NAME_VSPDB=rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
     - MYSQL_SERVER_NAME_ReadVSPDB=rdsmysql-8469.c31ahitxrkg7.us-west-2.rds.amazonaws.com
     - MYSQL_DATABASE_NAME=VSS-TagFileAuth-Alpha
     - MYSQL_USERNAME=root
     - MYSQL_ROOT_PASSWORD=d3vRDS1234_ 