version: '2'
services:
  webapi:
    image: 940327799086.dkr.ecr.us-west-2.amazonaws.com/rpd-ccss-tagfileauth-webapi:latest
    env_file:
     - docker-compose-dev.env
    volumes:
      - ./artifacts/logs:/app/logs 
    depends_on:
      - schema
    ports:
      - 7001:80 
    