version: '2.1'

services:
  vss.raptor.service.webapi:
    image: username/vss.raptor.service.webapi:Debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "80:80"
    volumes:
      - .:/app
