{{- $filename := printf "%s.txt" .Values.environment -}}
{{- $configName := printf "%s-cfg-%s" .Release.Name .Values.environment | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  labels:
    app: {{ template "tagfileauthservice.name" . }}
    release: {{ template "tagfileauthservice.name" . }}
data:
  {{ range .Files.Lines $filename }}
  {{ . }}{{ end }}


