apiVersion: v1
kind: Service
metadata:
  name: {{ template "docker-registry.fullname" . }}
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}

spec:
  selector:
    app: {{ template "docker-registry.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: https
    port: 5000
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
