{{ if .Values.utilities.deploy }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trex.deployname" . }}-utils
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
    immutable-cluster: "true"
    mutable-cluster: "true"
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.psNodeReplicaCount }}
  template:
    metadata:
      labels:
        # This label has to be added to the selector's section of 
        # ignite-service.yaml so that the Kubernetes Ignite lookup service
        # can easily track all Ignite pods available deployed so far.
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-utils
        immutable-cluster: "true"
        mutable-cluster: "true"
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
{{- with .Values.nodeSelector.none }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations.none }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        # Custom Ignite pod name.
      - name: ignite-node
        # Ignite Docker image. Kubernetes IP finder is supported starting from
        # Apache Ignite 2.3.0
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.Utils
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        resources:
{{ toYaml .Values.resources | indent 10 }}
        envFrom:
        - configMapRef:
            name: {{ template "trex.config" . }}
        command: ["bash"]
        args: ["-c", "sleep 1d"]

        #env:
        # Ignite's Docker image parameter. Adding the jar file that
        # contain TcpDiscoveryKubernetesIpFinder implementation.
        #- name: OPTION_LIBS
        #  value: ignite-kubernetes
        # Ignite's Docker image parameter. Passing the Ignite configuration
        # to use for an Ignite pod.
        #- name: CONFIG_URI
        #  value: file:////data/ignite/example-kube.xml
        ports:
{{ toYaml .Values.trexPorts | indent 8 }}

        volumeMounts:
        # Mounting the storage with the Ignite configuration.
        #- mountPath: "/data/ignite"
        #  name: ignite-storage
        env:
          - name: IGNITE_HOME
            value: "/trex/"
          - name: IS_KUBERNETES
            value: "true"
          - name: DEPLOYED_ENV
            value: {{ .Values.environment }}
          - name: TREX_IGNITE_JVM_MAX_HEAP_SIZE_MB
            value: {{ .Values.utilities.javaHeapMaxSizeMb | quote }}
          - name: TREX_IGNITE_JVM_INITIAL_HEAP_SIZE_MB
            value: {{ .Values.utilities.javaHeapInitialSizeMb | quote }}  
{{ end }}