{{- $configName := printf "%s-config-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trex.deployname" . }}-csg
  labels:
    app: {{ template "trex.deployname" . }}
    chart: {{ template "trex.chart" . }}
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: {{ .Values.connectedSiteGateway.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "trex.deployname" . }}
        component: {{ template "trex.deployname" . }}-csg
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}

      containers:
      - name: webapi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}.ConnectedSiteGateway
        
        resources:
{{ toYaml .Values.connectedSiteGateway.resources | indent 10 }}  
        
        envFrom:
        - configMapRef:
            name: {{ $configName }}
        
        ports:
        - containerPort: 80
        
        command: ["dotnet"]
        args: ["VSS.TRex.ConnectedSite.Gateway.WebApi.dll"]


        