kind: Service
apiVersion: v1
metadata:
  name: {{ template "trex.deployname" . }}-csg
spec:
  selector:
    component: {{ template "trex.deployname" . }}-csg
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP