resources:
  repositories:
    - repository: k8s
      type: git
      name: VSS/k8s
trigger:
  branches:
    include:
    - '*'
variables:
  MAJOR_VERSION: 3
  MINOR_VERSION: 0
  PATCH: $[counter(variables['MAJOR_VERSION'], 100)]
  BRANCH: $(Build.SourceBranchName)
jobs:
- template: build-helpers/templates/build-nuget.yaml@k8s
  parameters:
    solutionFileName: VSS.Authentication.sln
    pathToTestResults: '*.Tests\TestResults\TestResults.xml'
    codeCoverage: 'true'