{{- $configName := printf "%s-cfg-%s-%s" .Release.Name .Values.environment .Values.image.tag | lower | replace "_" "-" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}
    spec:
      containers:
      - image: 300213723870.dkr.ecr.us-west-2.amazonaws.com/vss-productivity3d-trex-support-tool:{{ .Values.image.tag }}
        name: {{ .Release.Name }}-{{ .Values.environment }}-{{ .Values.image.tag }}        
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
{{ toYaml .Values.resources | indent 12 }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ $configName }}
